= Overview

Launch a server (Elin Server) that work with hosts(Vim/Neovim in this case).
Elin Server connects to nREPL server and returns the processed result to hosts from Elin Server.

image:http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/liquidz/vim-elin/main/doc/graph/component.pum[Components]
image:http://www.plantuml.com/plantuml/proxy?src=https://raw.githubusercontent.com/liquidz/vim-elin/main/doc/graph/sequence.pum[Sequences]

== Basic Policy

* Implement UI-related processing on Vim/Neovim in Vim script.
* Handle interactions with the nREPL server and processing of data received from Vim/Neovim in Clojure (Babashka).
* Implement the Clojure side based on https://github.com/stuartsierra/component[stuartsierra/component].
* Define all settings related to each component explicitly in `resources/config.edn`.

== Directories

[cols="30,70a"]
|===

| components
| Various components

| constants
| Various constants

| handler
| Implementation of handlers called by the Handler component

| interceptor
| Implementation of interceptors called by the Interceptor component

| protocol
| Various protocols

| schema
| Various schemas

| function
| Provides concrete functionality using various components. The first argument always receives elin passed to the handler. Essentially, everything is synchronous.

|===

== Plugin

* Purpose
** Custom interceptors (expansion of existing features)
** Custom handlers (addition of new features)

== Interceptor

* includes, excludes
** includes take priority
*** Even if something is in excludes, if it is also in includes at the same time, it is enabled.
