==== Key mappings

Elin does not map any keys by default.
If you want to use the default key mappings, set `g:elin_enable_default_key_mappings` to true.

[source,vim]
----
let g:elin_enable_default_key_mappings = v:true
----

Default key mappings use `<Leader>` as a prefix.
If you want to change it to `<LocalLeader>`, set `g:elin_default_key_mapping_leader`.

[source,vim]
----
let g:elin_default_key_mapping_leader = '<LocalLeader>'
----

==== Reload

Elin provides <<ElinReload>> and <<ElinReloadAll>> commands for code reloading
similarly to
https://docs.cider.mx/cider/usage/code_reloading.html#using-clj-reload[cider-ns-refresh with clj-reload].
To support
https://www.cognitect.com/blog/2013/06/04/clojure-workflow-reloaded["reloaded" workflows],
set the provided before/after hook variables to qualified (namespaced),
zero-arity function names as in the following example:

[source,vim]
----
let g:elin#internal#nrepl#reload_before_fn = 'user/stop'
let g:elin#internal#nrepl#reload_after_fn = 'user/start'
----

The specified functions will then be evaluated before and after code reloading.

==== Selectors

To choose an item from multiple candidates, Elin uses a selector.
The behavior of the selector differs between Vim and Neovim.

===== Vim

It has its own implementation, and its behavior can be modified through selector plugins.
You can change which selector plugin to use by setting the selector name in `g:elin#internal#select#selector`.

[source,vim]
----
" Requires junegunn/fzf.vim
let g:elin#internal#select#selector = 'fzf'
----

===== Neovim

Elin uses https://neovim.io/doc/user/lua.html#vim.ui.select()[vim.ui.select()].
Therefore, you can use your preferred plugin to modify the behavior of `vim.ui.select()` like follows.

[example]
====
* https://github.com/nvim-telescope/telescope-ui-select.nvim
====

==== Status line

`elin#status` function returns the nREPL connection status text, and you can use it in the https://vim-jp.org/vimdoc-en/windows.html#status-line[status line].

.e.g. https://github.com/itchyny/lightline.vim[lightline.vim]
[source,vim]
----
let g:lightline = {
      \   'tabline': {
      \     'right': [['filetype', 'bufnum' ], ['elin'] ]
      \   },
      \   'component_function': {
      \     'elin': 'elin#status',
      \   },
      \ }
----

==== Integration with other plugins

There are some <<Plugin>> that can be used with Elin.

[cols="20a,30a,50a"]
|===
| Plugin | Description | URL

| coc.nvim
| Completion source
| https://github.com/liquidz/elin-coc-source

| nvim-cmp
| Completion source
| https://github.com/liquidz/elin-cmp-source

| telescope.nvim
| File selector
| https://github.com/liquidz/elin-telescope.nvim

|===
