==== Key mappings

Elin does not map any keys by default.
If you want to use the default key mappings, set `g:elin_enable_default_key_mappings` to true.

[source,vim]
----
let g:elin_enable_default_key_mappings = v:true
----

Default key mappings use `<Leader>` as a prefix.
If you want to change it to `<LocalLeader>`, set `g:elin_default_key_mapping_leader`.

[source,vim]
----
let g:elin_default_key_mapping_leader = '<LocalLeader>'
----

==== Selectors

To choose an item from multiple candidates, Elin uses a selector.
The behavior of the selector differs between Vim and Neovim.

===== Vim

It has its own implementation, and its behavior can be modified through selector plugins.
You can change which selector plugin to use by setting the selector name in `g:elin#internal#select#selector`.

[source,vim]
----
" Requires junegunn/fzf.vim
let g:elin#internal#select#selector = 'fzf'
----

===== Neovim

Elin uses https://neovim.io/doc/user/lua.html#vim.ui.select()[vim.ui.select()].
Therefore, you can use your preferred plugin to modify the behavior of `vim.ui.select()` like follows.

[example]
====
* https://github.com/nvim-telescope/telescope-ui-select.nvim
====

==== Integration with other plugins

There are some <<Plugin>> that can be used with Elin.

[cols="20a,30a,50a"]
|===
| Plugin | Description | URL

| coc.nvim
| Completion source
| https://github.com/liquidz/elin-coc-source

| nvim-cmp
| Completion source
| https://github.com/liquidz/elin-cmp-source

| telescope.nvim
| File selector
| https://github.com/liquidz/elin-telescope.nvim

|===
