= 🍏 elin
:sectnums:
:toc: left
:table-caption!:
:source-highlighter: rouge
:icons: font

// c.f. http://tholman.com/github-corners/ {{{
+++
<a href="https://github.com/liquidz/elin" class="github-corner" aria-label="View source on GitHub">
  <svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true">
    <path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path>
    <path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path>
    <path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path>
  </svg>
</a>
<style>
.github-corner { position: fixed; top: 0; right: 0; }
.github-corner:hover .octo-arm { animation:octocat-wave 560ms ease-in-out }
@keyframes octocat-wave { 0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)} }
@media (max-width:500px){ .github-corner:hover .octo-arm{ animation:none } .github-corner .octo-arm { animation:octocat-wave 560ms ease-in-out } }
</style>
+++
// }}}
// custom css {{{
+++
<style>
.xsmall { font-size: 0.7em; }
</style>
+++
// }}}
// variables {{{

:elin-config-edn: https://github.com/liquidz/elin/blob/main/resources/config.edn
:elin-format: https://github.com/liquidz/elin-format[elin-format]
:vim-iced: https://github.com/liquidz/vim-iced[vim-iced]
:cider: https://github.com/clojure-emacs/cider[CIDER]
:cljfmt: https://github.com/weavejester/cljfmt[cljfmt]
:cljstyle: https://github.com/greglook/cljstyle[cljstyle]
:clojure-lsp: https://clojure-lsp.io[clojure-lsp]
:shadow-cljs: https://github.com/thheller/shadow-cljs[shadow-cljs]

// }}}

include::./generated/variables.adoc[]

== Overview

https://github.com/liquidz/elin[elin] is a Clojure development environment, primarily written in https://babashka.org[Babashka].

This project is being developed as the successor to {vim-iced} and, as same as vim-iced, is heavily inspired by {CIDER}.

The goal of this project is to provide a server program that serves as the foundation for a Clojure development environment and its interface, enabling it to theoretically offer a Clojure development environment to any editor.

== Getting Started

include::./getting_started/index.adoc[]

== Evaluation

TODO

== Completion

TODO

== Formatting

Elin does not provide a default formatter for now.
The reason is that for format checks in CI, external tools such as {cljfmt}, {cljstyle}, or {clojure-lsp} are commonly used, and a formatter that only works within the editor is often unnecessary.

However, if you blocked when saving files in namespaces with large amounts of code due to the formatting entire buffer, you can use the {elin-format} plugin to format only the current form.

== Navigation

TODO

== Reference

TODO

== Macro

TODO

== Namespace

TODO

== Testing

TODO


== ClojureScript

include::./clojurescript/index.adoc[]


== Buffer

=== Information buffer

TODO

=== Temporal buffer

TODO


== Configuration
include::./configuration/index.adoc[]


== Plugin

The plugins are tagged with the `elin-clj-plugin` topic on GitHub, so you can view the list from the following link.

https://github.com/topics/elin-clj-plugin


== Handlers

Handlers process requests from the host editor.

=== Built-in Handlers

include::./generated/handlers.adoc[]


== Interceptors

Interceptors intercept various processes and change their behavior.

=== Built-in Interceptors
include::./generated/interceptors.adoc[]


== Host

=== Vim/Neovim

==== Commands

include::./generated/commands.adoc[]


== Cheatsheet

include::./cheatsheet.adoc[]

// vim:fdl=0:
