(ns elin.constant.interceptor
  "Constants for interceptor kinds"
  (:refer-clojure :exclude [test]))

(def all ::all)
(def autocmd ::autocmd)
(def configure-handler ::configure-handler)
(def connect ::connect)
(def debug ::debug)
(def disconnect ::disconnect)
(def evaluate ::evaluate)
(def handler ::handler)
(def http-request ::http-request)
(def http-route ::http-route)
(def modify-code ::modify-code)
(def nrepl ::nrepl)
(def output ::output)
(def quickfix ::quickfix)
(def raw-nrepl ::raw-nrepl)
(def tap ::tap)
(def test ::test)
(def test-result ::test-result)
